# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ir3mO4EcqhkxZBqW3_82Ev-LAm6RfrXg
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q datasets pandas matplotlib nltk

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datasets import load_dataset

pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 100)

dataset = load_dataset("ucberkeley-dlab/measuring-hate-speech", split="train")
df = dataset.to_pandas()

print(df.shape)



target_cols = [c for c in df.columns if c.startswith("target_") and pd.api.types.is_bool_dtype(df[c])]


broad_target_cols = [c for c in target_cols if c.count("_") == 1]
specific_target_cols = [c for c in target_cols if c not in broad_target_cols]

print(f"Broad target columns: {len(broad_target_cols)}")
print(broad_target_cols)

print(f"Specific target columns: {len(specific_target_cols)}")
specific_target_cols[:20]

rating_cols = [
    "sentiment", "respect", "insult", "humiliate", "status",
    "dehumanize", "violence", "genocide", "attack_defend",
    "hatespeech", "hate_speech_score"]
rating_cols = [c for c in rating_cols if c in df.columns]

grouped = df.groupby(["comment_id", "text"], as_index=False)

mean_df = grouped[rating_cols].mean()
max_df = grouped[target_cols].max()

comments = pd.merge(mean_df, max_df, on=["comment_id", "text"])



comments[target_cols] = comments[target_cols].astype(bool)

print(comments.shape)
comments.head(3)

import nltk
nltk.download("vader_lexicon")

from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

vader_scores = comments["text"].fillna("").apply(lambda x: sia.polarity_scores(x)).apply(pd.Series)
vader_scores = vader_scores.add_prefix("vader_")

# Drop vader_ columns if they already exist in comments to prevent duplicates on re-run
existing_vader_cols = [col for col in comments.columns if col.startswith('vader_')]
if existing_vader_cols:
    comments = comments.drop(columns=existing_vader_cols)

comments = pd.concat([comments, vader_scores], axis = 1)

comments.head()

id_cols = ["comment_id", "text", "hate_speech_score", "hatespeech", "vader_neg", "vader_neu", "vader_pos", "vader_compound"]


comments_unique_cols = comments.loc[:, ~comments.columns.duplicated()]

target_long = comments_unique_cols.melt(
    id_vars=id_cols,
    value_vars=specific_target_cols,
    var_name="target",
    value_name="is_target"
)


target_long = target_long[target_long["is_target"]].copy()


split_df = target_long["target"].str.extract(r"target_(?P<family>[^_]+)_(?P<subgroup>.+)")


target_long["target_family"] = split_df["family"].str.title()
subgroup_clean = split_df["subgroup"].str.replace("_", " ").str.title()


target_long["target_clean"] = target_long["target_family"] + ": " + subgroup_clean